### ISSUE TITLE
Notes with the same name don't show the folder path.

### ISSUE THREAD

**Issue by Provmawn** [ThisTheThe/MicroMike#1]
Notes with the same name located in different folders don't show the folder name making it difficult to link to the correct note that I want to link to.

 MicroMike Theme:
![image](https://github.com/user-attachments/assets/5dc0e8e8-9185-499b-a1a7-cd42cf2841ce)

Default Theme:
![image](https://github.com/user-attachments/assets/38e84fc4-cc89-462d-bb06-e87e9404238b)

**Comment by ThisTheThe** [comment]
I'll update to fix that. When you have, see "Show Suggestion Directory" in the style settings.

**Comment by Provmawn** [comment]
It works! Thank you!
